### ISSUE TITLE
Error despues de clonar el template

### ISSUE THREAD

**Issue by DanvDev02** [ITESO-ESI/002-pointers#1]
CMake Error at C:/Program Files/JetBrains/CLion 2022.2.1/bin/cmake/win/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Criterion (missing: CRITERION_LIBRARY CRITERION_INCLUDE_DIR)

Marca este error justo despues de abrir en Clion el template, saludos.

**Comment by DevCam** [comment]
en el `CMakeLists.txt` [principal](../blob/master/CMakeLists.txt) comentar la linea `9`

```cmake
# add_subdirectory(tests)
```

o instalar (criterion)[https://github.com/Snaipe/Criterion]
